#!/bin/bash
on_exit(){
  rm art*
  day-night-cycle
  exit 0
}

token=$(curl -H "Authorization: Basic

ENTER 64 BIT VERSION OF CLIENT_ID:CLIENT_SECRET

" -d grant_type=refresh_token -d refresh_token=

ENTER REFRESH TOKEN

https://accounts.spotify.com/api/token)

tok=$(echo $token | jq -r '.access_token')
gsettings set org.gnome.desktop.background picture-options 'scaled'
if ! pgrep -x spotify >/dev/null; then
  echo ""; exit
fi
cmd="org.freedesktop.DBus.Properties.Get"
domain="org.mpris.MediaPlayer2"
path="/org/mpris/MediaPlayer2"
count=0
art=""
trap 'on_exit' SIGINT
while true
do
  if [ "$count" -ge 3000 ]; then
    token=$(curl -H "Authorization: Basic

    ENTER 64 BIT VERSION OF CLIENT_ID:CLIENT_SECRET

    " -d grant_type=refresh_token -d refresh_token=

    ENTER REFRESH TOKEN

    https://accounts.spotify.com/api/token)


    tok=$(echo $token | jq -r '.access_token')
  fi
  meta=$(dbus-send --print-reply --dest=${domain}.spotify \
    /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:${domain}.Player string:Metadata)

  idnew=$(echo "$meta" | sed -nr '/xesam:url"/,+2s/^ +variant +string "(.*)"$/\1/p' | tail -1 | sed "s/[(][^)]*[)]//g" | sed 's@.*/@@')
  if [ "$id" != "$idnew" ]; then
    id="$idnew"
    artnew=$(curl -X "GET" "https://api.spotify.com/v1/tracks/$id" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $tok")

    artnew=$(echo $artnew | jq -r '.album.images[0].url')
  fi

  if [ "$art" != "$artnew" ]; then
    rm art*
    art="$artnew"
    wget -O "art$id" $art
    /usr/bin/gsettings set org.gnome.desktop.background picture-uri "file:///home/abraham/Spotify Background/art$id"
  fi
  count=$(( $count+10 ))
  sleep 10
done
